version: "3"

services:
  backend:
    build: ./server
    expose:
      - "5000"

  frontend:
    build: ./client
    expose:
      - "3000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
